import { z } from "zod";

/** Priority levels a staging checklist item can carry, lowest → highest. */
export const CHECKLIST_PRIORITIES = ["Critical", "High", "Standard"] as const;
/** One of {@link CHECKLIST_PRIORITIES}. */
export type ChecklistPriority = (typeof CHECKLIST_PRIORITIES)[number];

/** Fixed category taxonomy for staging checklist items. */
export const CHECKLIST_CATEGORIES = [
  "DIY/Declutter",
  "Rental Inventory",
  "Minor Repair",
] as const;
/** One of {@link CHECKLIST_CATEGORIES}. */
export type ChecklistCategory = (typeof CHECKLIST_CATEGORIES)[number];

/**
 * A single pre-listing checklist entry generated by AI for a room,
 * stored on `Room.checklistItems` as JSON and rendered in the lookbook.
 */
export type ChecklistItem = {
  /** What to do, phrased as an actionable task. */
  item: string;
  /** Which {@link ChecklistCategory} the task belongs to. */
  category: ChecklistCategory;
  /** How urgent the task is ({@link ChecklistPriority}). */
  priority: ChecklistPriority;
};

/**
 * Zod schema for a well-formed `ChecklistItem`.
 *
 * Purpose: validates AI/JSON input in the canonical shape — `category`
 * and `priority` must be exact enum members. Use
 * {@link parseChecklistItems} for lenient parsing of legacy/persisted
 * rows (alias normalization, drop-on-invalid).
 */
export const checklistItemSchema = z.object({
  item: z.string(),
  category: z.enum(CHECKLIST_CATEGORIES),
  priority: z.enum(CHECKLIST_PRIORITIES),
});

const PRIORITY_ALIASES: Record<string, ChecklistPriority> = {
  Critical: "Critical",
  High: "High",
  Standard: "Standard",
  high: "Critical",
  medium: "High",
  low: "Standard",
};

const storedChecklistItemSchema = z.object({
  item: z.string(),
  category: z.enum(CHECKLIST_CATEGORIES),
  priority: z.string().transform((value, ctx) => {
    const normalized = PRIORITY_ALIASES[value];
    if (!normalized) {
      ctx.addIssue({
        code: z.ZodIssueCode.custom,
        message: `Unknown checklist priority: ${value}`,
      });
      return z.NEVER;
    }
    return normalized;
  }),
});

/**
 * Leniently parses persisted/AI checklist JSON into `ChecklistItem[]`.
 *
 * Purpose: render-side guard for `Room.checklistItems`, which may hold
 * legacy shapes (priorities like `"high"`/`"medium"`/`"low"` are
 * normalized up the ladder: high→Critical, medium→High, low→Standard).
 *
 * Contract: never throws. Non-array input yields `[]`; malformed entries
 * are dropped individually, each drop logged with a `roomId`-tagged
 * warning. Output items are always fully valid `ChecklistItem`s.
 *
 * Side effects: logs warnings to `console.warn` (one per dropped item,
 * plus one for non-array input). No env vars or providers needed.
 *
 * @param value Raw JSON value (typically from `Room.checklistItems`).
 * @param options Optional `{ roomId }` used only to tag warning logs.
 * @returns Parsed checklist items, in input order, skipping invalid
 *   entries; `[]` for non-array input.
 */
export function parseChecklistItems(
  value: unknown,
  options?: { roomId?: string }
): ChecklistItem[] {
  const prefix = options?.roomId ? `[checklist roomId=${options.roomId}]` : "[checklist]";

  if (!Array.isArray(value)) {
    console.warn(`${prefix} checklistItems is not an array; rendering without checklist`);
    return [];
  }

  const items: ChecklistItem[] = [];
  value.forEach((entry, index) => {
    const result = storedChecklistItemSchema.safeParse(entry);
    if (!result.success) {
      console.warn(
        `${prefix} dropping malformed checklist item at index ${index}: ${result.error.issues
          .map((issue) => issue.message)
          .join("; ")}`
      );
      return;
    }
    items.push(result.data);
  });

  return items;
}
