import { NextRequest, NextResponse } from "next/server";

import { getAuthedPrismaUser } from "@/lib/api-auth";
import { prisma } from "@/lib/prisma";
import { PREVIEW_TOKEN_QUERY_PARAM, signPreviewToken } from "@/lib/preview-token";
import {
  BROWSERLESS_TIMEOUT_MS,
  buildBrowserlessPdfBody,
  buildBrowserlessPdfUrl,
} from "@/lib/browserless";

// cuid() as generated by Prisma: "c" + 24 lowercase alphanumerics (25 chars).
// Anchored so nothing that could alter the preview URL path (slashes, dots,
// query characters) is ever accepted.
const PROJECT_ID_PATTERN = /^c[a-z0-9]{24}$/;

export async function POST(req: NextRequest) {
  try {
    // 1. Session auth. Fail closed before touching any paid quota.
    const user = await getAuthedPrismaUser();
    if (!user) {
      return NextResponse.json(
        {
          error: "Unauthorized",
          message: "You must be signed in to export a PDF",
        },
        { status: 401 }
      );
    }

    // 2. Shape-validate projectId BEFORE it is interpolated into the
    //    preview URL handed to an external service.
    const { projectId } = await req.json();
    if (typeof projectId !== "string" || !PROJECT_ID_PATTERN.test(projectId)) {
      return NextResponse.json(
        {
          error: "Invalid projectId",
          message: "Project ID is required to generate PDF",
        },
        { status: 400 }
      );
    }

    // 3. Ownership check — before spending Browserless quota.
    const project = await prisma.project.findUnique({
      where: { id: projectId },
      select: { userId: true },
    });
    if (!project || project.userId !== user.id) {
      return NextResponse.json(
        { error: "Project not found", message: "Project does not exist" },
        { status: 404 }
      );
    }

    // 4. App URL: the cloud browser must be able to reach this deployment.
    //    A localhost default is only ever valid in development.
    let appUrl = process.env.NEXT_PUBLIC_APP_URL;
    if (!appUrl || appUrl.trim() === "") {
      if (process.env.NODE_ENV === "production") {
        console.error(
          "PDF export misconfigured: NEXT_PUBLIC_APP_URL must be set in production (public URL of this deployment)."
        );
        return NextResponse.json(
          {
            error: "Configuration missing",
            message:
              "PDF export is not properly configured. Please contact support.",
          },
          { status: 500 }
        );
      }
      appUrl = "http://localhost:3000";
    }

    const apiKey = process.env.BROWSERLESS_API_KEY;
    if (!apiKey) {
      return NextResponse.json(
        {
          error: "Configuration missing",
          message:
            "PDF export service is not properly configured. Please contact support.",
        },
        { status: 500 }
      );
    }

    // 5. Signed, short-lived, projectId-scoped token lets the cookie-less
    //    headless browser through middleware auth for THIS project only.
    const token = await signPreviewToken(projectId);
    const previewUrl = `${appUrl}/projects/${projectId}/preview?${PREVIEW_TOKEN_QUERY_PARAM}=${encodeURIComponent(token)}`;

    // 6. Credential rides in a header (Basic auth, `apiKey:`), never the
    //    query string; bounded by an AbortController so a hung Browserless
    //    call cannot hold the request open forever.
    const controller = new AbortController();
    const timeoutId = setTimeout(
      () => controller.abort(),
      BROWSERLESS_TIMEOUT_MS
    );

    let chromeResponse: Response;
    try {
      chromeResponse = await fetch(buildBrowserlessPdfUrl(), {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          Authorization: `Basic ${Buffer.from(`${apiKey}:`).toString("base64")}`,
        },
        body: JSON.stringify(buildBrowserlessPdfBody(previewUrl)),
        signal: controller.signal,
      });
    } finally {
      clearTimeout(timeoutId);
    }

    if (!chromeResponse.ok) {
      const errorText = await chromeResponse.text();
      console.error("Browserless API error:", chromeResponse.status, errorText);

      if (chromeResponse.status === 401 || chromeResponse.status === 403) {
        return NextResponse.json(
          {
            error: "Authentication failed",
            message:
              "PDF export service authentication failed. Please contact support.",
          },
          { status: chromeResponse.status }
        );
      }

      if (chromeResponse.status === 429) {
        return NextResponse.json(
          {
            error: "Rate limit exceeded",
            message:
              "PDF export service is busy. Please wait a moment and try again.",
            retryable: true,
          },
          { status: 429 }
        );
      }

      return NextResponse.json(
        {
          error: "PDF generation failed",
          message: "Unable to generate PDF at this time. Please try again.",
          retryable: true,
        },
        { status: chromeResponse.status }
      );
    }

    // 7. Sanity-check the payload really is a PDF before streaming it to
    //    the user (e.g. an HTML error page slipped through with a 200).
    const pdfBuffer = await chromeResponse.arrayBuffer();
    const contentType = chromeResponse.headers.get("content-type") ?? "";
    const leadingBytes = String.fromCharCode(
      ...new Uint8Array(pdfBuffer.slice(0, 4))
    );
    if (
      pdfBuffer.byteLength === 0 ||
      !contentType.includes("application/pdf") ||
      leadingBytes !== "%PDF"
    ) {
      console.error(
        "Browserless returned a non-PDF response:",
        contentType,
        pdfBuffer.byteLength,
        "bytes"
      );
      return NextResponse.json(
        {
          error: "PDF generation failed",
          message: "Unable to generate PDF at this time. Please try again.",
          retryable: true,
        },
        { status: 502 }
      );
    }

    return new NextResponse(pdfBuffer, {
      status: 200,
      headers: {
        "Content-Type": "application/pdf",
        "Content-Disposition": `attachment; filename="project-${projectId}.pdf"`,
      },
    });
  } catch (error) {
    console.error("PDF export error:", error);

    if (error instanceof Error && error.name === "AbortError") {
      return NextResponse.json(
        {
          error: "PDF export timed out",
          message:
            "PDF generation took too long. Please try again in a moment.",
          retryable: true,
        },
        { status: 504 }
      );
    }

    const errorMessage =
      error instanceof Error ? error.message : "Internal server error";

    if (errorMessage.includes("fetch") || errorMessage.includes("network")) {
      return NextResponse.json(
        {
          error: "Network error",
          message:
            "Unable to reach the PDF export service. Please check your connection and try again.",
          retryable: true,
        },
        { status: 503 }
      );
    }

    return NextResponse.json(
      {
        error: "PDF export failed",
        message:
          "An unexpected error occurred while generating the PDF. Please try again.",
        retryable: true,
      },
      { status: 500 }
    );
  }
}
